name: blackroad_v1
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.3.6
  crypto: ^3.0.3
  dio: ^5.3.2
  dotted_border: 2.0.0+3
  equatable: ^2.0.0
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_dynamic_links: ^5.3.5
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_image_compress: ^2.0.4
  flutter_keyboard_visibility: ^5.4.1
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.3
  google_sign_in: ^6.1.5
  intl: ^0.18.0
  pin_code_fields: ^7.3.0
  pin_input_text_field: 4.1.0
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.0.0
  upgrader: ^8.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
        - asset: assets/fonts/LatoMedium.ttf
          weight: 500
        - asset: assets/fonts/LatoExtraBold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSansBold.ttf
          weight: 700
